# Generated by Django 3.2.9 on 2021-11-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='products',
            field=models.ManyToManyField(null=True, to='products.OrderProduct'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ждет обработку', 'Ждет обработку'), ('Готовится', 'Готовится'), ('Готов', 'Готов'), ('Выполнен', 'Выполнен')], default=('Ждет обработку', 'Ждет обработку'), max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
