# Generated by Django 3.2.9 on 2021-11-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211117_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='products',
            field=models.ManyToManyField(to='products.OrderProduct'),
        ),
    ]
