# Generated by Django 3.2.9 on 2021-11-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_case_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
