# Generated by Django 3.2.9 on 2021-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order', to='products.OrderProduct'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ждет обработку', 'Ждет обработку'), ('Готовится', 'Готовится'), ('Готов', 'Готов'), ('Выполнен', 'Выполнен'), ('Отменён', 'Отменён')], default='Ждет обработку', max_length=20),
        ),
    ]
