# Generated by Django 3.2.9 on 2021-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличными', 'Наличными'), ('Картой', 'Картой')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ждет обработку', 'Ждет обработку'), ('Готовится', 'Готовится'), ('Готов', 'Готов'), ('Выполнен', 'Выполнен'), ('Отменён', 'Отменён')], default='Ждет обработку', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
