# Generated by Django 3.2.9 on 2021-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211126_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='raitng',
        ),
        migrations.AlterField(
            model_name='review',
            name='raitng',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Рейтинг'),
        ),
    ]
